name: reviewdog

on: [pull_request]

jobs:
  eslint:
    name: 'eslint (node: ${{ matrix.node }}, os: ${{ matrix.os }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: 'github-check'
          eslint_flags: '. --ext .js,.vue --ignore-path .gitignore'
  stylelint:
    name: 'stylelint (node: ${{ matrix.node }}, os: ${{ matrix.os }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - uses: reviewdog/action-stylelint@v1
        with:
          reporter: 'github-check'
          stylelint_input: 'src/**/*.css src/**/*.vue'
  prettier:
    name: 'prettier (node: ${{ matrix.node }}, os: ${{ matrix.os }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: 'github-check'
